# make common phrases next

spanish = [
    {"Spanish": "el", "English": "the"},
    {"Spanish": "de", "English": "of"},
    {"Spanish": "que", "English": "that"},
    {"Spanish": "y", "English": "and"},
    {"Spanish": "a", "English": "a"},
    {"Spanish": "en", "English": "in"},
    {"Spanish": "un", "English": "an"},
    {"Spanish": "ser", "English": "to be"},
    {"Spanish": "se", "English": "oneself"},
    {"Spanish": "no", "English": "no"},
    {"Spanish": "haber", "English": "to have"},
    {"Spanish": "por", "English": "by"},
    {"Spanish": "con", "English": "with"},
    {"Spanish": "su", "English": "his"},
    {"Spanish": "para", "English": "for"},
    {"Spanish": "como", "English": "like"},
    {"Spanish": "estar", "English": "to be"},
    {"Spanish": "tener", "English": "to have"},
    {"Spanish": "le", "English": "him"},
    {"Spanish": "lo", "English": "the"},
    {"Spanish": "lo", "English": "it"},
    {"Spanish": "todo", "English": "all"},
    {"Spanish": "pero", "English": "but"},
    {"Spanish": "más", "English": "more"},
    {"Spanish": "hacer", "English": "to do"},
    {"Spanish": "o", "English": "or"},
    {"Spanish": "poder", "English": "to be able"},
    {"Spanish": "decir", "English": "to say"},
    {"Spanish": "este", "English": "this"},
    {"Spanish": "ir", "English": "to go"},
    {"Spanish": "otro", "English": "other"},
    {"Spanish": "ese", "English": "that"},
    {"Spanish": "la", "English": "the"},
    {"Spanish": "si", "English": "if"},
    {"Spanish": "me", "English": "me"},
    {"Spanish": "ya", "English": "already"},
    {"Spanish": "ver", "English": "to see"},
    {"Spanish": "porque", "English": "because"},
    {"Spanish": "dar", "English": "to give"},
    {"Spanish": "cuando", "English": "when"},
    {"Spanish": "él", "English": "he"},
    {"Spanish": "muy", "English": "very"},
    {"Spanish": "sin", "English": "without"},
    {"Spanish": "vez", "English": "time"},
    {"Spanish": "mucho", "English": "a lot"},
    {"Spanish": "saber", "English": "to know"},
    {"Spanish": "qué", "English": "what"},
    {"Spanish": "sobre", "English": "about, on"},
    {"Spanish": "mi", "English": "my"},
    {"Spanish": "alguno", "English": "some"},
    {"Spanish": "mismo", "English": "same"},
    {"Spanish": "yo", "English": "I"},
    {"Spanish": "también", "English": "also"},
    {"Spanish": "hasta", "English": "until"},
    {"Spanish": "año", "English": "year"},
    {"Spanish": "dos", "English": "two"},
    {"Spanish": "querer", "English": "to want"},
    {"Spanish": "entre", "English": "between"},
    {"Spanish": "así", "English": "so"},
    {"Spanish": "primero", "English": "first"},
    {"Spanish": "desde", "English": "from"},
    {"Spanish": "grande", "English": "big"},
    {"Spanish": "eso", "English": "that"},
    {"Spanish": "ni", "English": "neither"},
    {"Spanish": "nos", "English": "us"},
    {"Spanish": "llegar", "English": "to arrive"},
    {"Spanish": "pasar", "English": "to pass"},
    {"Spanish": "tiempo", "English": "time"},
    {"Spanish": "ella", "English": "she"},
    {"Spanish": "sí", "English": "yes"},
    {"Spanish": "día", "English": "day"},
    {"Spanish": "uno", "English": "one"},
    {"Spanish": "bien", "English": "well"},
    {"Spanish": "poco", "English": "small"},
    {"Spanish": "deber", "English": "to owe"},
    {"Spanish": "entonces", "English": "then"},
    {"Spanish": "poner", "English": "to put"},
    {"Spanish": "cosa", "English": "thing"},
    {"Spanish": "tanto", "English": "so much"},
    {"Spanish": "hombre", "English": "man"},
    {"Spanish": "parecer", "English": "to seem"},
    {"Spanish": "nuestro", "English": "our"},
    {"Spanish": "tan", "English": "so"},
    {"Spanish": "donde", "English": "where"},
    {"Spanish": "ahora", "English": "now"},
    {"Spanish": "parte", "English": "part"},
    {"Spanish": "después", "English": "after"},
    {"Spanish": "vida", "English": "life"},
    {"Spanish": "quedar", "English": "to stay"},
    {"Spanish": "siempre", "English": "always"},
    {"Spanish": "creer", "English": "to believe"},
    {"Spanish": "hablar", "English": "to speak"},
    {"Spanish": "llevar", "English": "to carry"},
    {"Spanish": "dejar", "English": "to leave"},
    {"Spanish": "nada", "English": "nothing"},
    {"Spanish": "cada", "English": "each"},
    {"Spanish": "seguir", "English": "to follow"},
    {"Spanish": "menos", "English": "less"},
    {"Spanish": "nuevo", "English": "new"},
    {"Spanish": "encontrar", "English": "to find"},
    {"Spanish": "gente", "English": "people"},
    {"Spanish": "momento", "English": "moment"},
    {"Spanish": "siquiera", "English": "even"}
    ]

french = [
    {"French": "le", "English": "the"},
    {"French": "de", "English": "of"},
    {"French": "un", "English": "a"},
    {"French": "à", "English": "to"},
    {"French": "être", "English": "to be"},
    {"French": "et", "English": "and"},
    {"French": "en", "English": "in"},
    {"French": "avoir", "English": "to have"},
    {"French": "que", "English": "that"},
    {"French": "pour", "English": "for"},
    {"French": "dans", "English": "in"},
    {"French": "ce", "English": "this"},
    {"French": "il", "English": "he"},
    {"French": "qui", "English": "who"},
    {"French": "ne", "English": "not"},
    {"French": "sur", "English": "on"},
    {"French": "se", "English": "oneself"},
    {"French": "pas", "English": "not"},
    {"French": "plus", "English": "more"},
    {"French": "pouvoir", "English": "to be able"},
    {"French": "par", "English": "by"},
    {"French": "je", "English": "I"},
    {"French": "avec", "English": "with"},
    {"French": "tout", "English": "all"},
    {"French": "faire", "English": "to do, to make"},
    {"French": "son", "English": "his, her"},
    {"French": "mettre", "English": "to put"},
    {"French": "autre", "English": "other"},
    {"French": "on", "English": "one"},
    {"French": "mais", "English": "but"},
    {"French": "nous", "English": "we"},
    {"French": "comme", "English": "like, as"},
    {"French": "ou", "English": "or"},
    {"French": "si", "English": "if"},
    {"French": "leur", "English": "their"},
    {"French": "lui", "English": "him, her"},
    {"French": "devoir", "English": "to have to, must"},
    {"French": "prendre", "English": "to take"},
    {"French": "aussi", "English": "also"},
    {"French": "notre", "English": "our"},
    {"French": "sans", "English": "without"},
    {"French": "jour", "English": "day"},
    {"French": "alors", "English": "then"},
    {"French": "deux", "English": "two"},
    {"French": "bien", "English": "well"},
    {"French": "venir", "English": "to come"},
    {"French": "encore", "English": "again"},
    {"French": "là", "English": "there"},
    {"French": "très", "English": "very"},
    {"French": "sous", "English": "under"},
    {"French": "non", "English": "no"},
    {"French": "même", "English": "same"},
    {"French": "quelque", "English": "some"},
    {"French": "y", "English": "there"},
    {"French": "voir", "English": "to see"},
    {"French": "elle", "English": "she"},
    {"French": "depuis", "English": "since"},
    {"French": "peu", "English": "little"},
    {"French": "on", "English": "we"},
    {"French": "trouver", "English": "to find"},
    {"French": "donner", "English": "to give"},
    {"French": "savoir", "English": "to know"},
    {"French": "falloir", "English": "to be necessary"},
    {"French": "prendre", "English": "to take"},
    {"French": "venir", "English": "to come"},
    {"French": "encore", "English": "again"},
    {"French": "voir", "English": "to see"},
    {"French": "elle", "English": "she"},
    {"French": "depuis", "English": "since"},
    {"French": "peu", "English": "little"},
    {"French": "on", "English": "we"},
    {"French": "trouver", "English": "to find"},
    {"French": "donner", "English": "to give"},
    {"French": "savoir", "English": "to know"},
    {"French": "falloir", "English": "to be necessary"},
    {"French": "venir", "English": "to come"},
    {"French": "encore", "English": "again"},
    {"French": "voir", "English": "to see"},
    {"French": "elle", "English": "she"},
    {"French": "depuis", "English": "since"},
    {"French": "peu", "English": "little"},
    {"French": "on", "English": "we"},
    {"French": "trouver", "English": "to find"},
    {"French": "donner", "English": "to give"},
    {"French": "savoir", "English": "to know"},
    {"French": "falloir", "English": "to be necessary"},
    {"French": "aller", "English": "to go"},
    {"French": "grand", "English": "big"},
    {"French": "penser", "English": "to think"},
    {"French": "avant", "English": "before"},
    {"French": "temps", "English": "time"},
    {"French": "dernier", "English": "last"},
    {"French": "très", "English": "very"},
    {"French": "premier", "English": "first"},
    {"French": "chose", "English": "thing"},
    {"French": "venir", "English": "to come"},
    {"French": "encore", "English": "again"},
    {"French": "voir", "English": "to see"},
    {"French": "elle", "English": "she"},
    {"French": "depuis", "English": "since"},
    {"French": "peu", "English": "little"},
    {"French": "on", "English": "we"},
    {"French": "trouver", "English": "to find"},
    {"French": "donner", "English": "to give"},
    {"French": "savoir", "English": "to know"},
    {"French": "falloir", "English": "to be necessary"}
]

german = [
    {"German": "der", "English": "the"},
    {"German": "die", "English": "the"},
    {"German": "und", "English": "and"},
    {"German": "in", "English": "in"},
    {"German": "zu", "English": "to"},
    {"German": "den", "English": "the"},
    {"German": "das", "English": "the"},
    {"German": "mit", "English": "with"},
    {"German": "sich", "English": "oneself"},
    {"German": "des", "English": "of"},
    {"German": "auf", "English": "on"},
    {"German": "für", "English": "for"},
    {"German": "ist", "English": "is"},
    {"German": "im", "English": "in"},
    {"German": "dem", "English": "the"},
    {"German": "nicht", "English": "not"},
    {"German": "ein", "English": "a"},
    {"German": "Die", "English": "the"},
    {"German": "eine", "English": "a"},
    {"German": "als", "English": "than"},
    {"German": "auch", "English": "also"},
    {"German": "es", "English": "it"},
    {"German": "an", "English": "at"},
    {"German": "werden", "English": "to become"},
    {"German": "aus", "English": "out"},
    {"German": "er", "English": "he"},
    {"German": "hat", "English": "has"},
    {"German": "nach", "English": "after"},
    {"German": "wird", "English": "will"},
    {"German": "sind", "English": "are"},
    {"German": "durch", "English": "through"},
    {"German": "man", "English": "one"},
    {"German": "oder", "English": "or"},
    {"German": "über", "English": "over"},
    {"German": "wir", "English": "we"},
    {"German": "mehr", "English": "more"},
    {"German": "sagte", "English": "said"},
    {"German": "zum", "English": "to the"},
    {"German": "haben", "English": "to have"},
    {"German": "mehr", "English": "more"},
    {"German": "sein", "English": "to be"},
    {"German": "jetzt", "English": "now"},
    {"German": "so", "English": "so"},
    {"German": "ihm", "English": "him"},
    {"German": "wie", "English": "how"},
    {"German": "keine", "English": "no"},
    {"German": "seine", "English": "his"},
    {"German": "soll", "English": "should"},
    {"German": "bei", "English": "at"},
    {"German": "ihr", "English": "her"},
    {"German": "nun", "English": "now"},
    {"German": "auch", "English": "also"},
    {"German": "nur", "English": "only"},
    {"German": "wenn", "English": "when"},
    {"German": "dann", "English": "then"},
    {"German": "unsere", "English": "our"},
    {"German": "ihr", "English": "their"},
    {"German": "was", "English": "what"},
    {"German": "zeit", "English": "time"},
    {"German": "so", "English": "so"},
    {"German": "kann", "English": "can"},
    {"German": "kein", "English": "no"},
    {"German": "aber", "English": "but"},
    {"German": "zu", "English": "too"},
    {"German": "viel", "English": "much"},
    {"German": "werden", "English": "to be"},
    {"German": "können", "English": "to be able"},
    {"German": "ich", "English": "I"},
    {"German": "nichts", "English": "nothing"},
    {"German": "du", "English": "you"},
    {"German": "hatte", "English": "had"},
    {"German": "sie", "English": "she"},
    {"German": "nach", "English": "after"},
    {"German": "da", "English": "there"},
    {"German": "seine", "English": "its"},
    {"German": "über", "English": "about"},
    {"German": "auch", "English": "also"},
    {"German": "zwei", "English": "two"},
    {"German": "mehr", "English": "more"},
    {"German": "jahr", "English": "year"},
    {"German": "beim", "English": "at the"},
    {"German": "zur", "English": "to the"},
    {"German": "vor", "English": "before"},
    {"German": "denn", "English": "because"},
    {"German": "man", "English": "one"},
    {"German": "sonst", "English": "otherwise"},
    {"German": "wo", "English": "where"},
    {"German": "wurde", "English": "became"},
    {"German": "uns", "English": "us"},
    {"German": "doch", "English": "yet"},
    {"German": "gegen", "English": "against"},
    {"German": "ihr", "English": "you"},
    {"German": "sein", "English": "his"},
    {"German": "durch", "English": "by"},
    {"German": "können", "English": "can"},
    {"German": "vielleicht", "English": "maybe"},
    {"German": "unsere", "English": "our"},
    {"German": "wieder", "English": "again"},
    {"German": "sein", "English": "to be"},
    {"German": "sogar", "English": "even"},
    {"German": "einen", "English": "a"},
    {"German": "einfach", "English": "simple"},
    {"German": "machen", "English": "to make"},
    {"German": "dann", "English": "then"},
    {"German": "sein", "English": "to be"},
    {"German": "gibt", "English": "gives"},
    {"German": "wenn", "English": "when"},
    {"German": "diese", "English": "these"},
    {"German": "gut", "English": "good"},
    {"German": "zu", "English": "too"},
    {"German": "wollen", "English": "to want"}
]
vietnamese = [
    {"Vietnamese": "và", "English": "and"},
    {"Vietnamese": "trong", "English": "in"},
    {"Vietnamese": "không", "English": "not"},
    {"Vietnamese": "có", "English": "have"},
    {"Vietnamese": "là", "English": "is"},
    {"Vietnamese": "với", "English": "with"},
    {"Vietnamese": "cho", "English": "for"},
    {"Vietnamese": "đã", "English": "already"},
    {"Vietnamese": "từ", "English": "from"},
    {"Vietnamese": "như", "English": "like"},
    {"Vietnamese": "được", "English": "to be"},
    {"Vietnamese": "nó", "English": "it"},
    {"Vietnamese": "một", "English": "one"},
    {"Vietnamese": "vài", "English": "a few"},
    {"Vietnamese": "cái", "English": "thing"},
    {"Vietnamese": "của", "English": "of"},
    {"Vietnamese": "anh", "English": "brother"},
    {"Vietnamese": "em", "English": "younger brother/sister"},
    {"Vietnamese": "chị", "English": "older sister"},
    {"Vietnamese": "bạn", "English": "friend"},
    {"Vietnamese": "tôi", "English": "I"},
    {"Vietnamese": "ông", "English": "Mr."},
    {"Vietnamese": "bà", "English": "Mrs."},
    {"Vietnamese": "cô", "English": "aunt"},
    {"Vietnamese": "dì", "English": "aunt"},
    {"Vietnamese": "chú", "English": "uncle"},
    {"Vietnamese": "cậu", "English": "uncle"},
    {"Vietnamese": "con", "English": "child"},
    {"Vietnamese": "người", "English": "person"},
    {"Vietnamese": "này", "English": "this"},
    {"Vietnamese": "đó", "English": "that"},
    {"Vietnamese": "kia", "English": "there"},
    {"Vietnamese": "đây", "English": "here"},
    {"Vietnamese": "nơi", "English": "place"},
    {"Vietnamese": "khi", "English": "when"},
    {"Vietnamese": "còn", "English": "still"},
    {"Vietnamese": "nhưng", "English": "but"},
    {"Vietnamese": "cũng", "English": "also"},
    {"Vietnamese": "nào", "English": "which"},
    {"Vietnamese": "ở", "English": "at"},
    {"Vietnamese": "đi", "English": "go"},
    {"Vietnamese": "lại", "English": "again"},
    {"Vietnamese": "lên", "English": "up"},
    {"Vietnamese": "xuống", "English": "down"},
    {"Vietnamese": "ra", "English": "out"},
    {"Vietnamese": "vào", "English": "in"},
    {"Vietnamese": "trước", "English": "before"},
    {"Vietnamese": "sau", "English": "after"},
    {"Vietnamese": "bây", "English": "now"},
    {"Vietnamese": "rồi", "English": "then"},
    {"Vietnamese": "về", "English": "about"},
    {"Vietnamese": "đến", "English": "to"},
    {"Vietnamese": "thì", "English": "then"},
    {"Vietnamese": "mới", "English": "new"},
    {"Vietnamese": "xong", "English": "finish"},
    {"Vietnamese": "chưa", "English": "not yet"},
    {"Vietnamese": "nhanh", "English": "fast"},
    {"Vietnamese": "chậm", "English": "slow"},
    {"Vietnamese": "tốt", "English": "good"},
    {"Vietnamese": "xấu", "English": "bad"},
    {"Vietnamese": "lạ", "English": "strange"},
    {"Vietnamese": "quen", "English": "familiar"},
    {"Vietnamese": "mới", "English": "just"},
    {"Vietnamese": "vừa", "English": "just"},
    {"Vietnamese": "ngay", "English": "day"},
    {"Vietnamese": "đêm", "English": "night"},
    {"Vietnamese": "buổi", "English": "session"},
    {"Vietnamese": "sáng", "English": "morning"},
    {"Vietnamese": "trưa", "English": "noon"},
    {"Vietnamese": "chiều", "English": "afternoon"},
    {"Vietnamese": "tối", "English": "evening"},
    {"Vietnamese": "hôm", "English": "day"},
    {"Vietnamese": "mai", "English": "tomorrow"},
    {"Vietnamese": "ngày", "English": "day"},
    {"Vietnamese": "tuần", "English": "week"},
    {"Vietnamese": "tháng", "English": "month"},
    {"Vietnamese": "năm", "English": "year"},
    {"Vietnamese": "hôm", "English": "day"},
    {"Vietnamese": "qua", "English": "past"},
    {"Vietnamese": "mỗi", "English": "each"},
    {"Vietnamese": "hoặc", "English": "or"},
    {"Vietnamese": "vì", "English": "because"},
    {"Vietnamese": "đang", "English": "is"},
    {"Vietnamese": "đã", "English": "already"},
    {"Vietnamese": "sẽ", "English": "will"},
    {"Vietnamese": "thì", "English": "then"},
    {"Vietnamese": "đều", "English": "all"},
    {"Vietnamese": "cũng", "English": "also"},
    {"Vietnamese": "mới", "English": "just"},
    {"Vietnamese": "vừa", "English": "just"},
    {"Vietnamese": "chỉ", "English": "only"},
    {"Vietnamese": "nếu", "English": "if"},
    {"Vietnamese": "khi", "English": "when"},
    {"Vietnamese": "mà", "English": "but"},
    {"Vietnamese": "hay", "English": "or"},
    {"Vietnamese": "về", "English": "about"},
    {"Vietnamese": "như", "English": "like"},
    {"Vietnamese": "đều", "English": "all"}
]
